[versions]
minestom = "461c56e749"
kotstom = "0.4.0-alpha.0"
minigamelib = "0.1.0-beta.0"
coroutines = "1.9.0-RC"
jansi = "2.4.1"
logback = "1.5.6"
polar = "1.11.1"
dotenv = "6.4.1"

[libraries]
minestom = { module = "net.minestom:minestom-snapshots", version.ref = "minestom" }
minigamelib = { module = "net.bladehunt:minigame-lib", version.ref = "minigamelib" }
kotstom-core = { module = "net.bladehunt:kotstom", version.ref = "kotstom" }
kotstom-serialization = { module = "net.bladehunt:kotstom-serialization", version.ref = "kotstom" }
polar = { module = "dev.hollowcube:polar", version.ref = "polar" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }

jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
kotstom = ["kotstom-core", "kotstom-serialization"]
logback = ["jansi", "logback-core", "logback-classic"]